engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  nodesecurity:
    enabled: false
ratings:
  paths:
  - "app/**"
  - "config/**"
  - "lib/**"
  - "app.js"
exclude_paths:
- "**/vendor/"
- "test/"
- "gulp/"
