options:
  formatter: stylish
  merge-default-rules: true
files:
  include: '**/*.s+(a|c)ss'
rules:
  bem-depth: 1
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  quotes:
    - 1
    - style: double
