language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
install:
  - bundle install
  - npm install
script:
  - npm run lint
  - npm run test:unit
  - npm run test:acceptance-ci
env:
  global:
  - HEROKU_APP_NAME=nhsbeta
  - secure: UaLZiWiB0ALtHVh+7JABzXqrACMGj/U5ZtYt7Ki/0mka6RtXmJ9RsQQkGCx7tq19BpaY7XSLRboBDv1T52u/9msY/KjkkRBkZHNJnT3Un2et5jeiBnJXZbZbSUIo1NtLGbkndoDVw2EiVp+DzaK3ilUuTV0g1z1tD0//0ltAwQ95vg52rxPcix4Ps7Q8mo5hq+Xwr7cILkKw+HkmYqiJd2TuaiFHsuzivN6UQA46kcm7S4iARlFCe5BoJTFJvIzrLQyamAS1yNb2JXTVAlXBbGeRD0GlH7qqQu2vfS9EDqdemQOeBu8niSaFhY6EUgV9LQr9uiOmeQkRKJplHilgPq04vZiUR9jCBxlKY089Tpk5wegg5/2PYdaodUFav8D1fdYuLakW/Tw1Slagk018WIWcmv8jul+aSUm/74aOxvY/Aaqm0ox7px7hmmi2k9//w+alq1m5Q+X1iBUkYehN9coWrqnSZwgPrgAigslKw1oYt7+p38pUKS8yulagjvxtmUUY3qA/FAv1cNf3sHgSiPELtyGHwhCaytYqw8rh/LKiAttBIWFlCWw+VuGavKYPgLcOJhBcPaueVOdMHHax6BVXlEUhB3Qc17QDrXN4iObspE0JzY+YvFkJfcyWodMOYILvjp/5xzOlpFu2ixS/v+p2//Ix/nzAD/OH6leiN8s=
  - secure: v3N2K0sMV0hRNSq0nMUvY7IxPOf7+vuEMf/gSD54X3dzo4JBwPFePqbLFeYQwq8Mv39mz7+G4QjfQc5RbTN4u0reCqx1rNeBJPmvBjbfLuFGuytgvY3yGVC0XJOfNDyULE132tmj2P6ctbd7hsVUMnJz6nnLk6P5rhXUUkZ+VVrFADdKBxZJj44Iv/9gWSpgSCtS4akX5DY9G2NriBcu3HaD0WnLVEpIRcc8pP0/+LgfLjHE9ihwnbQevLSb0fbIhhDIy9U+Q1lsrhN+TKKJE8AV8wffdgAiPpjzDFBv6OouuTh4D+qUBQK5BLMI0got95whlDDf0mDCc7AVa9jAkBU0wQ66qbxohPILQR/9+1nGi4pQ6Wtr4qG/CDlnZVN48xjw3iDiO09KO1jOGqtLKVvde+OMMlAiNeD3WmTkVuVsqvkqsYQ1tghZQEum5jVztWtZYfIiH1nodYdYCH7s47PqWa61OZCF1hPiPQ9cpNa+qPMbi/I900hpsUVdseYYRpDQrIz/fMWU7TIomEbzZ4/M8VMahBGbnkCHT5MgLFls1Xe74evdVU4d5WjBkL2UU4eZXocjeal6tCW96DSvpwGJvXHnxP3evKvycHWUSAFMxbcZZEWk5rmqKWhXRYn97jIavQwglh1xrQctd62YCcI0M2SZj70UBQyeE3HWHMs=
  - secure: arQ3XbKi8Kv9gs6sO26lKhwynbanYailVcuV7nGjihz3Vq1Be7YIiOKMBPYwdDoZyusCa4kxKAP2vTs18CoLi3hPlhd9Y8TxWpfXhmb/jpL+6DSw8jI6Ymvl6luJJ+yHXDuiIPsaxnsx2OzvlkZSVH5kj7XO2fgr6wR21uIHhxNnk4/QTmPic7gnDXmdFV69Lbnzut7NJY7Ey0gqs/TAC5nsU4dIAq5MSJLTmTQCyU9AKtzkI+M4hjo6zdSGOlgdvK4Zooa3XGkytMUooS/VpxJbNmbP4IfQBr00Pm4s/PK1ebvbLh7j3Lzox4fJTprXCIhFaiZ1SoneV5vwyF/xOoazPLwpPHSrVNEojyx+CS1iPiHzFQgpR+gQ1XU8eCEjAG/5Ppvvv6qFX1fm16Qbs0dkGm0pykWZ378CcNYS8FY1Cyfc1r4u6Qdp1bgW+mE8Fi3xJy2BuTZAfvqx6zqWef+/jdrk/gGPfVGXp3hTxk8TtdznAlzWYevVJxZUHQcyOiwYFEcT6ZlBhEicfYyYAUx7kQCmOiZkdSMS7I0JYZnmQWSutCTh+kyzQpsOJeS7vDoNqvMlRAyPV5uLrPLF5bjKBfGax5XePtbaYng9REYPgoQwHIIXrfGauY8sFPpKftYf8w1i1EIu5ejmkirV1MZ9LMydpklMLi0mnKYw4Sw=
